[project]
name = "scrna-longformer"
version = "0.1.0"
description = "kNN-masked gene-token transformer for scRNA-seq (PBMC3k MVP)"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
