seed: 42
device_preference: auto

data:
  npz_path: data/pbmc3k_hvg_knn.npz
  emb_out: data/pbmc3k_emb_cls.npy
  model_out: data/scrna_longformer_cls.pt
  labels: data/pbmc3k_labels.npy
  train_frac: 0.8
  batch_size: 8
  num_workers: 0
  mask_k: 16
  zscore: true

model:
  d_model: 128
  depth: 2
  n_heads: 4
  mlp_ratio: 4
  pool: mean
  n_classes: auto

train:
  epochs: 5
  lr: 3e-4
  weight_decay: 0.01
  log_every: 20
