seed: 42
device_preference: auto

data:
  npz_path: data/pbmc3k_hvg_knn_leiden.npz  # Real PBMC data with leiden clusters
  emb_out: data/pbmc3k_emb_cls.npy
  model_out: data/scrna_longformer_cls.pt
  labels: data/pbmc3k_labels.npy
  train_frac: 0.8
  batch_size: 16          # Reasonable batch size for real data
  num_workers: 0
  mask_k: 16              # kNN mask for attention
  zscore: false           # Data already properly scaled

model:
  d_model: 128            # Good capacity for real biological data  
  depth: 2                # Sufficient depth
  n_heads: 4              # Multiple attention heads
  mlp_ratio: 4            # Standard MLP ratio
  pool: mean
  n_classes: auto

train:
  epochs: 5               # Sufficient training
  lr: 3e-4                # Conservative learning rate
  weight_decay: 0.01
  log_every: 10
