seed: 42
device_preference: mps  # Try MPS again with smaller data

data:
  npz_path: data/pbmc3k_hvg_knn_leiden_small.npz  # Real leiden data but smaller
  emb_out: data/pbmc3k_emb_cls.npy
  model_out: data/scrna_longformer_cls.pt
  labels: data/pbmc3k_labels.npy
  train_frac: 0.3         # Small training subset
  batch_size: 32          # Moderate batch size
  num_workers: 0
  mask_k: 8               # Few neighbors
  zscore: false

model:
  d_model: 32             # Small model
  depth: 1                
  n_heads: 2              
  mlp_ratio: 2            
  pool: mean
  n_classes: auto

train:
  epochs: 2               # Quick training
  lr: 1e-3                
  weight_decay: 0.01
  log_every: 5
