seed: 42
device_preference: mps

data:
  npz_path: data/pbmc3k_hvg_knn_leiden_top500.npz
  emb_out: data/pbmc3k_emb_cls.npy
  model_out: data/scrna_longformer_cls.pt
  labels: data/pbmc3k_labels.npy
  train_frac: 0.8         # Use more training data
  batch_size: 32          
  num_workers: 0
  mask_k: 8               
  zscore: false

model:
  d_model: 8              # Tiny model for small data
  depth: 1                
  n_heads: 1              
  mlp_ratio: 1            # Minimal expansion
  pool: mean
  n_classes: auto

train:
  epochs: 10              # More epochs for small model
  lr: 1e-3                
  weight_decay: 0.1       # Strong regularization
  log_every: 5
