seed: 42
device_preference: auto

data:
  npz_path: data/pbmc3k_hvg_knn_fast.npz  # Use the fast synthetic data
  emb_out: data/pbmc3k_emb_cls.npy
  model_out: data/scrna_longformer_cls.pt
  labels: data/pbmc3k_labels.npy
  train_frac: 0.8
  batch_size: 32
  num_workers: 0
  mask_k: 16

model:
  d_model: 32             # Very small for fast debugging
  depth: 1                
  n_heads: 2              
  mlp_ratio: 2            
  pool: mean
  n_classes: auto

train:
  epochs: 1               # Just 1 epoch for debugging
  lr: 1e-3                
  weight_decay: 0.01
  log_every: 2            
