name: Container Check (manual)

on:
  workflow_dispatch: {}

jobs:
  container-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build preparation image (with cache)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: preparation/Dockerfile
          push: false
          tags: scrna-longformer:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run container check
        run: |
          docker run --rm scrna-longformer:ci python scripts/check_requirements.py
